# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_desc', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(default=0)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Region')),
            ],
        ),
        migrations.CreateModel(
            name='RoadConditionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true', models.IntegerField(default=1)),
                ('additional_info', models.TextField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('road_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.RoadCondition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
