# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accidents', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunction',
            name='mf_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MalfunctionType'),
        ),
        migrations.AddField(
            model_name='malfunction',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
        migrations.AddField(
            model_name='malfunction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vehicle'),
        ),
        migrations.AddField(
            model_name='application',
            name='malfunction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidents.Malfunction'),
        ),
        migrations.AddField(
            model_name='application',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
